### PR TITLE
milestone 16 (Searcing) Completed

### PR DESCRIPTION
**Pull request by shubhamfuloria**
some question are remaining, I'll come to that later. They seem out of my range now :smile:

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
Did  you have asked those questions on group ?

**Comment by shubhamfuloria** [comment]
Yes , in most of the questions there was TLE error , I tried to ask in group , but it didn't work .

**Comment by Vishal-raj-1** [comment]
OK, do one thing ..Check my solutions for those questions...It may be possible you need to optimize your code. I haven't written comments but you will understand whats going on...

So check them out.

**Comment by Manvityagi** [comment]
Yeah, @Vishal-raj-1 is right, You can check his solutions, and he can also help you if you don't understand them 

@Shubham10200

**Review by Manvityagi — APPROVED** [review]

**Comment by shubhamfuloria** [comment]
Ok . Thank you so much ! I'll check on Vishal's code , and try to understand things . Thank You So Much Vishal :)

**Pull request merged**
