### PR TITLE
milestone 19

### PR DESCRIPTION
**Pull request by shubhamfuloria**

### CODE REVIEW

**Review by Vishal-raj-1 — APPROVED** [review]
@Shubham10200 you  are doing great. you should work on indentation and remove some extra new lines at the end of functions.

Writing Time and Space complexity of a program is also a good practice.

**Review by Manvityagi — CHANGES_REQUESTED** [review]
@Shubham10200 you are doing great. you should work on indentation and remove some extra new lines at the end of functions.

Writing Time and Space complexity of a program is also a good practice.

Maybe You can try this, from this milestone itself, 

Credits: @Vishal-raj-1

**Comment by shubhamfuloria** [comment]
Ok I'll search what the `indentation` actually is . Thank you for suggesting :)

**Comment by Manvityagi** [comment]
> Ok I'll search what the `indentation` actually is . Thank you for suggesting :)

Proprt;y formatting your code, you can use any c++ formatting extension on vscode

**Comment by Vishal-raj-1** [comment]
Simply use `Shift` + `Alt` + `F` for formatting your code.

**Review by Manvityagi — APPROVED** [review]

**Pull request merged**
