### PR TITLE
Milestone-1

### PR DESCRIPTION
**Pull request by khushboog12**

### CODE REVIEW

**Review by Manvityagi — CHANGES_REQUESTED** [review]
You have deleted Sathvika's milestone 4. @khushboog12

**Comment by khushboog12** [comment]
I just uploaded my folder. I have even checked my recycle bin and it does not contain the required files.

**Comment by Manvityagi** [comment]
> I just uploaded my folder. I have even checked my recycle bin and it does not contain the required files.

Just see the file changed in the PR, you will be able to see your PR deletes Sathvika'a Milestone 4. 
It cant be merged this way. If you cant find Sathivka's file in your recycle bin, you can probably delete your fork and fork again and add your milestones again. Just save your milestones in a folder beforehand.

**Comment by khushboog12** [comment]
Okay, I'll fork it again.

**Pull request closed without merging**
